### ISSUE TITLE
Use try-except instead of separate in-check

### ISSUE THREAD

**Issue by WouterLVV** [dougmercer-yt/1brc#2]
Hiya,

Didn' t know how you wanted to manage this project, and didn't feel like this is worth an entire separate submission, so I'll shoot this in as an issue, but you can get a small but easy speed increase by using try-except. (Perhaps someone in the youtube comments also suggested this, I haven't checked).

If you replace
```
if city in result:
    item = result[city]
    item[0] += 1
    item[1] += temp_float
    item[2] = min(item[2], temp_float)
    item[3] = max(item[3], temp_float)
else:
    result[city] = [1, temp_float, temp_float, temp_float]
```
with:
```
try:
    item = result[city]
    item[0] += 1
    item[1] += temp_float
    item[2] = min(item[2], temp_float)
    item[3] = max(item[3], temp_float)
except KeyError:
    result[city] = [1, temp_float, temp_float, temp_float]
```

My results were:
```
Running pypy3 src/doug_booty4.py
0m33,887s
0m35,070s
0m33,911s
0m35,303s
0m34,285s

Running pypy3 src/doug_booty4_wouter.py
0m34,224s
0m31,989s
0m34,938s
0m33,997s
0m32,325s

Running pypy3 src/doug_booty4_alternate.py
0m37,423s
0m33,920s
0m35,533s
0m34,126s
0m33,809s

Running pypy3 src/doug_booty4_alternate_wouter.py
0m33,388s
0m33,408s
0m32,288s
0m31,747s
0m32,925s
```

**Comment by dougmercer** [comment]
This is a great idea.

Makes total sense that eating the cost of one exception is worth it to skip a ton of containment checks.

```
(1brc) ➜  1brc git:(main) ✗ bash eval.sh | python calc_stats.py
pypy3 src/community/doug_booty4_wouter.py: 9.365 seconds
pypy3 src/doug_booty4.py: 9.858 seconds
```

I'll add a src/community directory and add this version of the code. New fastest! =]

**Comment by dougmercer** [comment]
Just merged those changes in and shouted you out in the README =]

Thanks for suggesting this!
